### ISSUE TITLE
suggestions: summoning, recipes, and editing

### ISSUE THREAD

**Issue by TyoAtrosa** [ArtixAllMighty/PetBuddy2016#1]
tried out your mod and the new update, but updating to v2 causes my world to crash when trying to load the buddy. a few suggestions:

instead of the buddy appearing as soon as the world is loaded, make it to despawn whenever the world unloads and respawn when you use the summoning key or item. may help with the world loading crash.

allow renaming with a nametag to change the skin to another players, by putting a labeled nametag in the modifier slot. also allow renaming the pet buddy using the gui, so that the name doesn't glitch out anymore like it does for me.

allow the pet buddy to pick items that it is already carrying in its inventory, and maybe make an upgrade that allows it to automatically compress certain items if the recipe is available (like compressing cobble and netherack to free up space). 

add an activation item to receive the buddy, instead of recieving it automatically if a player doesn't want one. once  activated you would no longer need to use the item anymore to summon it.

**Comment by AbsolemJackdaw** [comment]
### instead of the buddy appearing as soon as the world is loaded, make it to despawn whenever the world unloads and respawn when you use the summoning key or item. may help with the world loading crash.

_the crash has nothing to do with the pet spawning. it's the chest inventory syncing client side. (which is saved to the player)_

### allow renaming with a nametag to change the skin to another players, by putting a labeled nametag in the modifier slot. also allow renaming the pet buddy using the gui, so that the name doesn't glitch out anymore like it does for me.

_it's planned. But 1.10 made a huge change as to how player textures are downloaded, and it is not as easy anymore as it used to be. I like the idea about putting the tag in the slot. didn't think about that yet... I'd love to know more about the name glitch though. first time I ever hear of that_

### allow the pet buddy to pick items that it is already carrying in its inventory, and maybe make an upgrade that allows it to automatically compress certain items if the recipe is available (like compressing cobble and netherack to free up space).

_not the first suggestion I have about picing up stuff. I'll probably restrict it to stuff that is already in his inventory so it doesn't get too op. and compacting blocks seems like its a little too op and can be abused to not smelt cobble into stone. unless you thought of something else by compacting_

### add an activation item to receive the buddy, instead of recieving it automatically if a player doesn't want one. once activated you would no longer need to use the item anymore to summon it.

_what's the point of not wanting one and installing the mod XD ? That's what we have the key summon for_

**Comment by TyoAtrosa** [comment]
as far as compression goes i'm thinking as in ExU's compressed cobblestone, sand, gravel and dirt, with sand gravel and dirt going up to quadruple compressed and cobble going to octuple, which only requires a crafting table to do, it's just time consuming to carry one around all the time. maybe by equiping a crafting table in the weapon slot it could auto compress compatible items for you, while losing the ability to attack.

as far as the summoning item or whatever, it's mainly just because not everyone on a server might want to use it, and as it is it is pretty op for a free item. maybe a config option to choose whether to get it for free on joining or requiring a summoning ritual or item for servers.

thanks for you reply, i really enjoyed the mod and hope to see more from you soon.

**Comment by AbsolemJackdaw** [comment]
maybe the pet should not join the world as the player logs in, but must be called expresivly by pressing P.
I understand where you come from with the idea to need to stow it and perform a ritual to get it.

That will have to be something for later on though. I'm trying to make the mod work correctly for now, then add all mpossible vanilla models.

as for the suggestion of compressed bricks etc, maybe someone can make a plugin/addon for my mod for the specific mod you mentioned. I don't know the mod, and rarely download any technical mods. 
I might implement in later on though, as sated before, after i finish the first two goals of the project.
