### ISSUE TITLE
suggestion 

### ISSUE THREAD

**Issue by SDUBZ** [ArtixAllMighty/PetBuddy2016#14]
tiny armor for the pet buddy and a stay command would be good

**Comment by AbsolemJackdaw** [comment]
armor is already implemented. not a full set, but there is some.
you can as well stow your pet instead of making him stay.
and a stay command is going to be hard to implement, because the pets need to be despawned if the player is too far away or non existant. kind-a counter current mechanics to make a stay command :/ sorry

**Comment by thada2607** [comment]
Hey, where are the stuff that my buddy stored after he dead? I can't seem to find it

**Comment by AbsolemJackdaw** [comment]
The stuff 'your buddy stores' is saved to the player, kind of like an ender chest. its independant from the buddy entity. so when your buddy respawns, it should just be back in its inventory. on death, he doesn't drop anything.

**Comment by omegadmm** [comment]
I noticed that when I die that Pet buddy loses his chest and all that is in it, but I believe that the item just becomes lost instead of dropping with all the stuff I had on me when I died. Is this how his storage behavior is suppose to work? I dislike the idea that if I die all he had is just gone. I understand if we both died, but usually with the way mobs only target me (twice is all I have seen of them attacking pet buddy and only after he did enough damage) he should be able to keep his stuff as he usually doesn't "die". Thanks for your time.

**Comment by AbsolemJackdaw** [comment]
It is not supposed to work like that.
the chest data is saved to the player indeed, but shouldnt be discarded on death !! Ill look into it

**Comment by AbsolemJackdaw** [comment]
fixed chest loss since 7e7e67402164c2699e64419736b6262f4da09242 (update 1.11)
armor already implemented , stay command would collide with how the mod is currently coded.
issue is concidered fixed (untill proven otherwise)
