### ISSUE TITLE
Crashing upon summoning

### ISSUE THREAD

**Issue by mar-x1** [ArtixAllMighty/PetBuddy2016#26]
when summoning pet buddy on my server, my friend crashes (latest version 1.12.2) and when using carryon mod to pick him up and set him down, I crash. Minecraft crash report says it is a rendering issue, so I assume this is a known issue, but I will copy a crash log on request

**Comment by AbsolemJackdaw** [comment]
always copy a crash ! no need asking

**Comment by GhostieComics** [comment]
I get a notification that says, crashed while ticking an entity. Only happens when my little my awesome Pet buddy is summoned and is moving about. Especially when he walks into me.

**Comment by AbsolemJackdaw** [comment]
the crash report will have important info for me , it pin points the problem in the code. i'd really like to see it, because now I can't really fix anything, as I cannot recreate the problem myself

**Comment by mar-x1** [comment]
I would, but it has been ages since this happened, and I don't think I have the files anymore

**Comment by GhostieComics** [comment]
Actually I apologize, I was trying to get back to this thread. See I downloaded the mod originally on 9minecraft and they had a 1.12 version, but when I went to curse forge I just redownloaded the most recent. My Amazing PetBuddy (god bless his pixels) has not given me a single problem since. Anyone considering this mod should download it right away, it's outstanding. Like seriously made the game awesome for solo play.

**Comment by AbsolemJackdaw** [comment]
thanks for the feedback ! also, feel free to tell everyone you know to get their mods from the official hosting sites ... CurseForge and Minecraft.net are the only ones I know of where people actually host them. all other sites are ripoffs, held by one person trying to make a profit of off other people's work
